### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by Inversion-NL**
Typo: istance -> instance

### CODE REVIEW

**Comment by mickem** [comment]
I'd prefer, if possible, to handle translations through https://poeditor.com/join/project/frV5jaW4lg as otherwise it will be a challenge for me to keep dual sync in sync...

**Comment by Inversion-NL** [comment]
Sorry.
Yes, however this is not a translation but a typo in English and I can't translate English?

**Comment by mickem** [comment]
It should be possible to translate the English as well, just make sure you have picked English as a language you work with...
But never used poeditor before, so not sure about all this :)

**Comment by Inversion-NL** [comment]
Ok, sorry, didn't know that. 
I'll try.

**Comment by mickem** [comment]
no worries.. Just me trying to out fancy translation stuff :)

**Comment by Inversion-NL** [comment]
Yes, English is also available for translation (which is a bit weird in essences, lol).

**Pull request merged**
